2024-12-17 12:43:56,025 - db_manager - INFO - Attempting to connect to MongoDB at 192.168.56.17:27017
2024-12-17 12:43:56,025 - db_manager - DEBUG - Connection Parameters: {'host': 'mongodb://192.168.56.17:27017/secure_document_db', 'tls': True, 'tlsCAFile': None, 'tlsAllowInvalidHostnames': False}
2024-12-17 12:43:56,030 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "message": "Starting topology monitoring"}
2024-12-17 12:43:56,031 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: []>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
2024-12-17 12:43:56,032 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "message": "Starting server monitoring"}
2024-12-17 12:43:56,034 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761720c951881049b615c74"}, "message": "Connection pool created", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:43:56,035 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6761720c951881049b615c74"}}
2024-12-17 12:43:56,038 - pymongo.serverSelection - DEBUG - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6761720c951881049b615c74"}, "remainingTimeMS": 29}
2024-12-17 12:43:56,042 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 7.080290999965655, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:56,043 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:56,549 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.13191599975471, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:56,550 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:57,057 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.589827000017976, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:57,058 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:57,564 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.096929000046657, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:57,565 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:58,072 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.083261999767274, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:58,073 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:58,579 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.522907000136911, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:58,580 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:59,087 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.939385000398033, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:59,088 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:43:59,595 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.603571999723499, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:43:59,596 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:00,103 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.763384999932896, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:00,104 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:00,610 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.386782999972638, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:00,612 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:01,119 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.735254000228451, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:01,120 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:01,628 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.635408000216557, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:01,630 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:02,136 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.726247000235162, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:02,137 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:02,643 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.1513820001455315, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:02,644 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:03,149 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.485013999783405, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:03,151 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:03,656 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.328145000272343, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:03,657 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:04,164 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.343439000171202, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:04,165 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:04,672 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 5.568059999859543, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:04,673 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:05,180 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.534242000318045, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:05,181 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:05,688 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.484140999920783, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:05,689 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:06,196 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.474798000046576, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:06,197 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:06,703 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.21885800005839, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:06,704 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:07,210 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.619052999714768, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:07,211 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:07,717 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.435586999989027, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:07,718 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:08,232 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.1268669997407414, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:08,234 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:08,740 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.6325009998327005, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:08,741 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:09,247 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.233276000377373, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:09,249 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:09,754 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.274145999715984, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:09,755 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:10,262 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.348851000031573, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:10,263 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:10,769 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.732137999781116, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:10,770 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:11,277 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.531841999778408, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:11,278 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:11,784 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.212263000226812, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:11,785 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:12,290 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.0001460001803935, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:12,291 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:12,797 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.253211000104784, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:12,798 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:13,304 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 3.8254959999903804, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:13,305 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:13,810 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.039963000195712, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:13,811 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:14,316 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.006016999937856, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:14,318 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:14,824 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 4.715149000276142, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:14,825 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:44:15,335 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 7.529793999765388, "failure": "\"AutoReconnect(\\\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\\\")\"", "message": "Server heartbeat failed"}
2024-12-17 12:44:15,337 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761720c951881049b615c74"}, "previousDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "newDescription": "<TopologyDescription id: 6761720c951881049b615c74, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect(\"SSL handshake failed: 192.168.56.17:27017: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')] (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)\")>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,686 - db_manager - INFO - Attempting to connect to MongoDB at 192.168.56.17:27017
2024-12-17 12:46:08,687 - db_manager - DEBUG - Connection Parameters: {'host': 'mongodb://192.168.56.17:27017/secure_document_db', 'tls': True, 'tlsCAFile': '/home/vagrant/certs/ca.crt', 'tlsAllowInvalidHostnames': False, 'tlsCertificateKeyFile': '/home/vagrant/certs/server/server.pem'}
2024-12-17 12:46:08,695 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "message": "Starting topology monitoring"}
2024-12-17 12:46:08,696 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "previousDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Unknown, servers: []>", "newDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,696 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017, "message": "Starting server monitoring"}
2024-12-17 12:46:08,698 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection pool created", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,699 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,701 - pymongo.serverSelection - DEBUG - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "remainingTimeMS": 29}
2024-12-17 12:46:08,706 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:08,707 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:08,710 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "driverConnectionId": 1, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "message": "Server heartbeat started"}
2024-12-17 12:46:08,713 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "driverConnectionId": 1, "serverConnectionId": 360, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 1.5982220002115355, "reply": "{\"helloOk\": true, \"ismaster\": true, \"topologyVersion\": {\"processId\": {\"$oid\": \"676168537cadccdfffe0e448\"}}, \"maxBsonObjectSize\": 16777216, \"maxMessageSizeBytes\": 48000000, \"maxWriteBatchSize\": 100000, \"localTime\": {\"$date\": \"2024-12-17T12:46:07.866Z\"}, \"logicalSessionTimeoutMinutes\": 30, \"connectionId\": 360, \"maxWireVersion\": 21, \"ok\": 1.0}", "message": "Server heartbeat succeeded"}
2024-12-17 12:46:08,714 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection pool ready", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,714 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "previousDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "newDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,715 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,716 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "driverConnectionId": 1, "serverConnectionId": 360, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": true, "message": "Server heartbeat started"}
2024-12-17 12:46:08,716 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,717 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection created", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,724 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:08,725 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:08,726 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:08,726 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:08,731 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection ready", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0025150389997179445}
2024-12-17 12:46:08,732 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.015770476999932725}
2024-12-17 12:46:08,733 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"buildinfo\": 1, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}, \"$db\": \"admin\"}", "commandName": "buildinfo", "databaseName": "admin", "requestId": 1957747793, "operationId": 1957747793, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,734 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 1.5579999999999998, "reply": "{\"version\": \"7.0.15\", \"gitVersion\": \"57939cc60865b0ce431c7e08c2589fa266a1a740\", \"allocator\": \"tcmalloc\", \"javascriptEngine\": \"mozjs\", \"sysInfo\": \"deprecated\", \"versionArray\": [7, 15], \"openssl\": {\"running\": \"OpenSSL 1.1.1f  31 Mar 2020\", \"compiled\": \"OpenSSL 1.1.1f  31 Mar 2020\"}, \"buildEnvironment\": {\"distmod\": \"ubuntu2004\", \"distarch\": \"x86_64\", \"cc\": \"/opt/mongodbtoolchain/v4/bin/gcc: gcc (GCC) 11.3.0\", \"ccflags\": \"-Werror -include mongo/platform/basic.h -ffp-contract=off -fasynchronous-unwind-tables -g2 -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -gdwarf-5 -fno-omit-frame-pointer -fno-strict-aliasing -O2 -march=sandybridge -mtune=generic -mprefer-vector-width=128 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-unused-but-set-variable -Wno-missing-braces -fstack-protector-strong -gdwarf64 -Wa,--nocompress-debug-sections -fno-builtin-memcmp -Wimplicit-fallthrough=5\", \"cxx\": \"/opt/mongodbtoolchain/v4/bin/g++: g++...", "commandName": "buildinfo", "databaseName": "admin", "requestId": 1957747793, "operationId": 1957747793, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,736 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,736 - db_manager - INFO - Successfully connected to MongoDB
2024-12-17 12:46:08,736 - db_manager - DEBUG - Server Information: {'version': '7.0.15', 'gitVersion': '57939cc60865b0ce431c7e08c2589fa266a1a740', 'modules': [], 'allocator': 'tcmalloc', 'javascriptEngine': 'mozjs', 'sysInfo': 'deprecated', 'versionArray': [7, 0, 15, 0], 'openssl': {'running': 'OpenSSL 1.1.1f  31 Mar 2020', 'compiled': 'OpenSSL 1.1.1f  31 Mar 2020'}, 'buildEnvironment': {'distmod': 'ubuntu2004', 'distarch': 'x86_64', 'cc': '/opt/mongodbtoolchain/v4/bin/gcc: gcc (GCC) 11.3.0', 'ccflags': '-Werror -include mongo/platform/basic.h -ffp-contract=off -fasynchronous-unwind-tables -g2 -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -gdwarf-5 -fno-omit-frame-pointer -fno-strict-aliasing -O2 -march=sandybridge -mtune=generic -mprefer-vector-width=128 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-unused-but-set-variable -Wno-missing-braces -fstack-protector-strong -gdwarf64 -Wa,--nocompress-debug-sections -fno-builtin-memcmp -Wimplicit-fallthrough=5', 'cxx': '/opt/mongodbtoolchain/v4/bin/g++: g++ (GCC) 11.3.0', 'cxxflags': '-Woverloaded-virtual -Wpessimizing-move -Wno-maybe-uninitialized -fsized-deallocation -Wno-deprecated -std=c++20', 'linkflags': '-Wl,--fatal-warnings -B/opt/mongodbtoolchain/v4/bin -gdwarf-5 -pthread -Wl,-z,now -fuse-ld=lld -fstack-protector-strong -gdwarf64 -Wl,--build-id -Wl,--hash-style=gnu -Wl,-z,noexecstack -Wl,--warn-execstack -Wl,-z,relro -Wl,--compress-debug-sections=none -Wl,-z,origin -Wl,--enable-new-dtags', 'target_arch': 'x86_64', 'target_os': 'linux', 'cppdefines': 'SAFEINT_USE_INTRINSICS 0 PCRE2_STATIC NDEBUG _XOPEN_SOURCE 700 _GNU_SOURCE _FORTIFY_SOURCE 2 ABSL_FORCE_ALIGNED_ACCESS BOOST_ENABLE_ASSERT_DEBUG_HANDLER BOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF BOOST_LOG_NO_SHORTHAND_NAMES BOOST_LOG_USE_NATIVE_SYSLOG BOOST_LOG_WITHOUT_THREAD_ATTR BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS BOOST_SYSTEM_NO_DEPRECATED BOOST_THREAD_USES_DATETIME BOOST_THREAD_VERSION 5'}, 'bits': 64, 'debug': False, 'maxBsonObjectSize': 16777216, 'storageEngines': ['devnull', 'wiredTiger'], 'ok': 1.0}
2024-12-17 12:46:08,736 - db_manager - INFO - Connected to Database: secure_document_db
2024-12-17 12:46:08,737 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "listDatabases", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,737 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "listDatabases", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,738 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,740 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0017703439998513204}
2024-12-17 12:46:08,741 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"listDatabases\": 1, \"nameOnly\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}, \"$db\": \"admin\"}", "commandName": "listDatabases", "databaseName": "admin", "requestId": 424238335, "operationId": 424238335, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,742 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 1.856, "reply": "{\"databases\": [{\"name\": \"admin\"}, {\"name\": \"config\"}, {\"name\": \"local\"}], \"ok\": 1.0}", "commandName": "listDatabases", "databaseName": "admin", "requestId": 424238335, "operationId": 424238335, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,743 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,743 - db_manager - INFO - Databases available: ['admin', 'config', 'local']
2024-12-17 12:46:08,744 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "listCollections", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,744 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "listCollections", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,745 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,745 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.00030137100020510843}
2024-12-17 12:46:08,746 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"listCollections\": 1, \"nameOnly\": true, \"filter\": {\"name\": \"users\"}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}, \"$db\": \"secure_document_db\"}", "commandName": "listCollections", "databaseName": "secure_document_db", "requestId": 719885386, "operationId": 719885386, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,747 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 1.0970000000000002, "reply": "{\"cursor\": {\"ns\": \"secure_document_db.$cmd.listCollections\"}, \"ok\": 1.0}", "commandName": "listCollections", "databaseName": "secure_document_db", "requestId": 719885386, "operationId": 719885386, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,747 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,748 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "<function writable_server_selector at 0x7fcd67daa160>", "operation": "create", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,748 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "<function writable_server_selector at 0x7fcd67daa160>", "operation": "create", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,748 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,749 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0002767860000858491}
2024-12-17 12:46:08,749 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"create\": \"users\", \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}, \"$db\": \"secure_document_db\"}", "commandName": "create", "databaseName": "secure_document_db", "requestId": 1649760492, "operationId": 1649760492, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,757 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 7.566, "reply": "{\"ok\": 1.0}", "commandName": "create", "databaseName": "secure_document_db", "requestId": 1649760492, "operationId": 1649760492, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,757 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,758 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "<function writable_server_selector at 0x7fcd67daa160>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,758 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "<function writable_server_selector at 0x7fcd67daa160>", "operation": "insert", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,759 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,759 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.00028853799994976725}
2024-12-17 12:46:08,760 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"insert\": \"users\", \"ordered\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}, \"$db\": \"secure_document_db\", \"documents\": [{\"name\": \"John Doe\", \"email\": \"john@example.com\", \"_id\": {\"$oid\": \"6761729010479612847339c4\"}}]}", "commandName": "insert", "databaseName": "secure_document_db", "requestId": 596516649, "operationId": 596516649, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,761 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 1.338, "reply": "{\"n\": 1, \"ok\": 1.0}", "commandName": "insert", "databaseName": "secure_document_db", "requestId": 596516649, "operationId": 596516649, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,761 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,762 - db_manager - INFO - Inserted document in users with ID: 6761729010479612847339c4
2024-12-17 12:46:08,763 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "message": "Starting topology monitoring"}
2024-12-17 12:46:08,763 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "previousDescription": "<TopologyDescription id: 6761729010479612847339c5, topology_type: Unknown, servers: []>", "newDescription": "<TopologyDescription id: 6761729010479612847339c5, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,764 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "serverHost": "192.168.56.17", "serverPort": 27017, "message": "Starting server monitoring"}
2024-12-17 12:46:08,764 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c5"}, "message": "Connection pool created", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,766 - __main__ - INFO - Connected to MongoDB
2024-12-17 12:46:08,766 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "driverConnectionId": 1, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "message": "Server heartbeat started"}
2024-12-17 12:46:08,767 - root - ERROR - Error in database manager: [Errno 2] No such file or directory
2024-12-17 12:46:08,767 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "PrimaryPreferred(tag_sets=None, max_staleness=-1, hedge=None)", "operation": "endSessions", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}}
2024-12-17 12:46:08,768 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "PrimaryPreferred(tag_sets=None, max_staleness=-1, hedge=None)", "operation": "endSessions", "topologyDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "clientId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,768 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 3.437151000071026, "failure": "\"AutoReconnect('192.168.56.17:27017: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')\"", "message": "Server heartbeat failed"}
2024-12-17 12:46:08,769 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,769 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c5"}, "previousDescription": "<TopologyDescription id: 6761729010479612847339c5, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "newDescription": "<TopologyDescription id: 6761729010479612847339c5, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('192.168.56.17:27017: connection closed (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,770 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0012751719996231259}
2024-12-17 12:46:08,771 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command started", "command": "{\"endSessions\": [{\"id\": {\"$binary\": {\"base64\": \"8gk5zEWBT/Wxyk0rqCut9A==\", \"subType\": \"04\"}}}], \"$db\": \"admin\"}", "commandName": "endSessions", "databaseName": "admin", "requestId": 1025202362, "operationId": 1025202362, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,772 - pymongo.command - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Command succeeded", "durationMS": 1.4009999999999998, "reply": "{\"ok\": 1.0}", "commandName": "endSessions", "databaseName": "admin", "requestId": 1025202362, "operationId": 1025202362, "driverConnectionId": 1, "serverConnectionId": 362, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,773 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:08,773 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017, "message": "Stopped server monitoring"}
2024-12-17 12:46:08,774 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection closed", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "reason": "Connection pool was closed", "error": "poolClosed"}
2024-12-17 12:46:08,774 - pymongo.connection - DEBUG - {"clientId": {"$oid": "6761729010479612847339c3"}, "message": "Connection pool closed", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:08,775 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "previousDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.0015982220002115355>]>", "newDescription": "<TopologyDescription id: 6761729010479612847339c3, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
2024-12-17 12:46:08,776 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "message": "Stopped topology monitoring"}
2024-12-17 12:46:08,776 - db_manager - INFO - MongoDB connection closed
2024-12-17 12:46:08,776 - root - ERROR - Error initializing the server: [Errno 2] No such file or directory
2024-12-17 12:46:09,218 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "6761729010479612847339c3"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": true, "durationMS": 502.50465299995994, "failure": "\"_OperationCancelled('operation cancelled')\"", "message": "Server heartbeat failed"}
2024-12-17 12:46:13,406 - db_manager - INFO - Attempting to connect to MongoDB at 192.168.56.17:27017
2024-12-17 12:46:13,406 - db_manager - DEBUG - Connection Parameters: {'host': 'mongodb://192.168.56.17:27017/secure_document_db', 'tls': True, 'tlsCAFile': '/home/vagrant/certs/ca.crt', 'tlsAllowInvalidHostnames': False, 'tlsCertificateKeyFile': '/home/vagrant/certs/server/server.pem'}
2024-12-17 12:46:13,415 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "message": "Starting topology monitoring"}
2024-12-17 12:46:13,416 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "previousDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Unknown, servers: []>", "newDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "message": "Topology description changed"}
2024-12-17 12:46:13,417 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "serverHost": "192.168.56.17", "serverPort": 27017, "message": "Starting server monitoring"}
2024-12-17 12:46:13,418 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection pool created", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,420 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "67617295cb493603004781a8"}}
2024-12-17 12:46:13,421 - pymongo.serverSelection - DEBUG - {"message": "Waiting for suitable server to become available", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "clientId": {"$oid": "67617295cb493603004781a8"}, "remainingTimeMS": 29}
2024-12-17 12:46:13,426 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:13,427 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:13,430 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "driverConnectionId": 1, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "message": "Server heartbeat started"}
2024-12-17 12:46:13,432 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "driverConnectionId": 1, "serverConnectionId": 364, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": false, "durationMS": 1.127614999859361, "reply": "{\"helloOk\": true, \"ismaster\": true, \"topologyVersion\": {\"processId\": {\"$oid\": \"676168537cadccdfffe0e448\"}}, \"maxBsonObjectSize\": 16777216, \"maxMessageSizeBytes\": 48000000, \"maxWriteBatchSize\": 100000, \"localTime\": {\"$date\": \"2024-12-17T12:46:12.586Z\"}, \"logicalSessionTimeoutMinutes\": 30, \"connectionId\": 364, \"maxWireVersion\": 21, \"ok\": 1.0}", "message": "Server heartbeat succeeded"}
2024-12-17 12:46:13,433 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection pool ready", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,433 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "previousDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Unknown, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Unknown, rtt: None>]>", "newDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "message": "Topology description changed"}
2024-12-17 12:46:13,434 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "buildinfo", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "clientId": {"$oid": "67617295cb493603004781a8"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,434 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,435 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "driverConnectionId": 1, "serverConnectionId": 364, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": true, "message": "Server heartbeat started"}
2024-12-17 12:46:13,436 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection created", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:13,442 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:13,444 - pymongo.ocsp_support - DEBUG - Peer did not staple an OCSP response
2024-12-17 12:46:13,444 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:13,445 - pymongo.ocsp_support - DEBUG - No authority access information, soft fail
2024-12-17 12:46:13,450 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection ready", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0026273400003447023}
2024-12-17 12:46:13,451 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0163316160001159}
2024-12-17 12:46:13,452 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command started", "command": "{\"buildinfo\": 1, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"5+FfJLNPRHC0BhhrKDdO8w==\", \"subType\": \"04\"}}}, \"$db\": \"admin\"}", "commandName": "buildinfo", "databaseName": "admin", "requestId": 1957747793, "operationId": 1957747793, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,453 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command succeeded", "durationMS": 1.479, "reply": "{\"version\": \"7.0.15\", \"gitVersion\": \"57939cc60865b0ce431c7e08c2589fa266a1a740\", \"allocator\": \"tcmalloc\", \"javascriptEngine\": \"mozjs\", \"sysInfo\": \"deprecated\", \"versionArray\": [7, 15], \"openssl\": {\"running\": \"OpenSSL 1.1.1f  31 Mar 2020\", \"compiled\": \"OpenSSL 1.1.1f  31 Mar 2020\"}, \"buildEnvironment\": {\"distmod\": \"ubuntu2004\", \"distarch\": \"x86_64\", \"cc\": \"/opt/mongodbtoolchain/v4/bin/gcc: gcc (GCC) 11.3.0\", \"ccflags\": \"-Werror -include mongo/platform/basic.h -ffp-contract=off -fasynchronous-unwind-tables -g2 -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -gdwarf-5 -fno-omit-frame-pointer -fno-strict-aliasing -O2 -march=sandybridge -mtune=generic -mprefer-vector-width=128 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-unused-but-set-variable -Wno-missing-braces -fstack-protector-strong -gdwarf64 -Wa,--nocompress-debug-sections -fno-builtin-memcmp -Wimplicit-fallthrough=5\", \"cxx\": \"/opt/mongodbtoolchain/v4/bin/g++: g++...", "commandName": "buildinfo", "databaseName": "admin", "requestId": 1957747793, "operationId": 1957747793, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,455 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:13,455 - db_manager - INFO - Successfully connected to MongoDB
2024-12-17 12:46:13,455 - db_manager - DEBUG - Server Information: {'version': '7.0.15', 'gitVersion': '57939cc60865b0ce431c7e08c2589fa266a1a740', 'modules': [], 'allocator': 'tcmalloc', 'javascriptEngine': 'mozjs', 'sysInfo': 'deprecated', 'versionArray': [7, 0, 15, 0], 'openssl': {'running': 'OpenSSL 1.1.1f  31 Mar 2020', 'compiled': 'OpenSSL 1.1.1f  31 Mar 2020'}, 'buildEnvironment': {'distmod': 'ubuntu2004', 'distarch': 'x86_64', 'cc': '/opt/mongodbtoolchain/v4/bin/gcc: gcc (GCC) 11.3.0', 'ccflags': '-Werror -include mongo/platform/basic.h -ffp-contract=off -fasynchronous-unwind-tables -g2 -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -gdwarf-5 -fno-omit-frame-pointer -fno-strict-aliasing -O2 -march=sandybridge -mtune=generic -mprefer-vector-width=128 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-unused-const-variable -Wno-unused-but-set-variable -Wno-missing-braces -fstack-protector-strong -gdwarf64 -Wa,--nocompress-debug-sections -fno-builtin-memcmp -Wimplicit-fallthrough=5', 'cxx': '/opt/mongodbtoolchain/v4/bin/g++: g++ (GCC) 11.3.0', 'cxxflags': '-Woverloaded-virtual -Wpessimizing-move -Wno-maybe-uninitialized -fsized-deallocation -Wno-deprecated -std=c++20', 'linkflags': '-Wl,--fatal-warnings -B/opt/mongodbtoolchain/v4/bin -gdwarf-5 -pthread -Wl,-z,now -fuse-ld=lld -fstack-protector-strong -gdwarf64 -Wl,--build-id -Wl,--hash-style=gnu -Wl,-z,noexecstack -Wl,--warn-execstack -Wl,-z,relro -Wl,--compress-debug-sections=none -Wl,-z,origin -Wl,--enable-new-dtags', 'target_arch': 'x86_64', 'target_os': 'linux', 'cppdefines': 'SAFEINT_USE_INTRINSICS 0 PCRE2_STATIC NDEBUG _XOPEN_SOURCE 700 _GNU_SOURCE _FORTIFY_SOURCE 2 ABSL_FORCE_ALIGNED_ACCESS BOOST_ENABLE_ASSERT_DEBUG_HANDLER BOOST_FILESYSTEM_NO_CXX20_ATOMIC_REF BOOST_LOG_NO_SHORTHAND_NAMES BOOST_LOG_USE_NATIVE_SYSLOG BOOST_LOG_WITHOUT_THREAD_ATTR BOOST_MATH_NO_LONG_DOUBLE_MATH_FUNCTIONS BOOST_SYSTEM_NO_DEPRECATED BOOST_THREAD_USES_DATETIME BOOST_THREAD_VERSION 5'}, 'bits': 64, 'debug': False, 'maxBsonObjectSize': 16777216, 'storageEngines': ['devnull', 'wiredTiger'], 'ok': 1.0}
2024-12-17 12:46:13,456 - db_manager - INFO - Connected to Database: secure_document_db
2024-12-17 12:46:13,456 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "listDatabases", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "clientId": {"$oid": "67617295cb493603004781a8"}}
2024-12-17 12:46:13,457 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "listDatabases", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "clientId": {"$oid": "67617295cb493603004781a8"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,458 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,458 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.000379953999981808}
2024-12-17 12:46:13,458 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command started", "command": "{\"listDatabases\": 1, \"nameOnly\": true, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"5+FfJLNPRHC0BhhrKDdO8w==\", \"subType\": \"04\"}}}, \"$db\": \"admin\"}", "commandName": "listDatabases", "databaseName": "admin", "requestId": 424238335, "operationId": 424238335, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,460 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command succeeded", "durationMS": 1.178, "reply": "{\"databases\": [{\"name\": \"admin\"}, {\"name\": \"config\"}, {\"name\": \"local\"}, {\"name\": \"secure_document_db\"}], \"ok\": 1.0}", "commandName": "listDatabases", "databaseName": "admin", "requestId": 424238335, "operationId": 424238335, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,460 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:13,461 - db_manager - INFO - Databases available: ['admin', 'config', 'local', 'secure_document_db']
2024-12-17 12:46:13,461 - pymongo.serverSelection - DEBUG - {"message": "Server selection started", "selector": "Primary()", "operation": "listCollections", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "clientId": {"$oid": "67617295cb493603004781a8"}}
2024-12-17 12:46:13,462 - pymongo.serverSelection - DEBUG - {"message": "Server selection succeeded", "selector": "Primary()", "operation": "listCollections", "topologyDescription": "<TopologyDescription id: 67617295cb493603004781a8, topology_type: Single, servers: [<ServerDescription ('192.168.56.17', 27017) server_type: Standalone, rtt: 0.001127614999859361>]>", "clientId": {"$oid": "67617295cb493603004781a8"}, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,462 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checkout started", "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,462 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked out", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1, "durationMS": 0.0003695119999065355}
2024-12-17 12:46:13,463 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command started", "command": "{\"listCollections\": 1, \"nameOnly\": true, \"filter\": {\"name\": \"users\"}, \"lsid\": {\"id\": {\"$binary\": {\"base64\": \"5+FfJLNPRHC0BhhrKDdO8w==\", \"subType\": \"04\"}}}, \"$db\": \"secure_document_db\"}", "commandName": "listCollections", "databaseName": "secure_document_db", "requestId": 719885386, "operationId": 719885386, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,465 - pymongo.command - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Command succeeded", "durationMS": 1.497, "reply": "{\"cursor\": {\"ns\": \"secure_document_db.$cmd.listCollections\", \"firstBatch\": [{\"name\": \"users\", \"type\": \"collection\"}]}, \"ok\": 1.0}", "commandName": "listCollections", "databaseName": "secure_document_db", "requestId": 719885386, "operationId": 719885386, "driverConnectionId": 1, "serverConnectionId": 366, "serverHost": "192.168.56.17", "serverPort": 27017}
2024-12-17 12:46:13,465 - pymongo.connection - DEBUG - {"clientId": {"$oid": "67617295cb493603004781a8"}, "message": "Connection checked in", "serverHost": "192.168.56.17", "serverPort": 27017, "driverConnectionId": 1}
2024-12-17 12:46:13,466 - db_manager - ERROR - Error initializing MongoDB connection: collection users already exists
Traceback (most recent call last):
  File "/home/vagrant/app/db_manager.py", line 71, in __init__
    self.db.create_collection('users')
  File "/home/vagrant/.local/lib/python3.8/site-packages/pymongo/_csot.py", line 119, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/vagrant/.local/lib/python3.8/site-packages/pymongo/synchronous/database.py", line 621, in create_collection
    raise CollectionInvalid("collection %s already exists" % name)
pymongo.errors.CollectionInvalid: collection users already exists
2024-12-17 12:46:13,467 - root - ERROR - Error in database manager: collection users already exists
2024-12-17 12:46:13,467 - root - ERROR - Error initializing the server: collection users already exists
2024-12-17 12:46:13,938 - pymongo.topology - DEBUG - {"topologyId": {"$oid": "67617295cb493603004781a8"}, "serverHost": "192.168.56.17", "serverPort": 27017, "awaited": true, "durationMS": 503.03617100007614, "failure": "\"_OperationCancelled('operation cancelled')\"", "message": "Server heartbeat failed"}
